import React, { useEffect, useState } from "react";
import http from "../api/http";
import SupplierSidebar from "./SupplierSidebar";

export default function MaterialCategories() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [items, setItems] = useState([]);
  const [saving, setSaving] = useState(false);
  const [success, setSuccess] = useState("");
  const [editingId, setEditingId] = useState("");
  const [editName, setEditName] = useState("");
  const [editDesc, setEditDesc] = useState("");
  const [actionError, setActionError] = useState("");
  const [q, setQ] = useState("");
  const [sort, setSort] = useState("name-asc");
  
  // Modal state
  const [modalOpen, setModalOpen] = useState(false);
  const [modalForm, setModalForm] = useState({
    categoryId: "",
    name: "",
    description: "",
    measurementType: ""
  });
  const [modalErrors, setModalErrors] = useState({});
  const [toasts, setToasts] = useState([]);

  // Toast function
  const toast = (message, variant = "success") => {
    const id = Date.now() + Math.random();
    setToasts((t) => [...t, { id, message, variant }]);
    setTimeout(() => setToasts((t) => t.filter((x) => x.id !== id)), 3000);
  };

  // Generate category ID (will be auto-generated by backend)
  const generateCategoryId = () => {
    return `CAT-${String(items.length + 1).padStart(3, '0')}`;
  };

  // Note: Subcategory IDs are now generated by the backend to ensure global uniqueness

  // Open modal
  const openModal = async () => {
    try {
      // Get the next available category ID from backend
      const res = await http.get("/api/material-categories/next-category-id");
      const nextId = res.data.nextCategoryId;
      
      console.log("Received next category ID from backend:", nextId); // Debug log
      
      setModalForm({
        categoryId: nextId,
        name: "",
        description: "",
        measurementType: ""
      });
      setModalErrors({});
      setModalOpen(true);
    } catch (error) {
      console.error("Failed to get next category ID:", error);
      // Fallback to local generation if API fails
      const fallbackId = generateCategoryId();
      console.log("Using fallback category ID:", fallbackId); // Debug log
      
      setModalForm({
        categoryId: fallbackId,
        name: "",
        description: "",
        measurementType: ""
      });
      setModalErrors({});
      setModalOpen(true);
      toast("Failed to get next category ID. Using fallback.", "error");
    }
  };

  // Close modal
  const closeModal = () => {
    setModalOpen(false);
    setModalForm({
      categoryId: "",
      name: "",
      description: "",
      measurementType: ""
    });
    setModalErrors({});
  };

  // Simple category validation
  const validateCategoryForm = () => {
    const errors = {};
    
    // Category ID validation
    if (!modalForm.categoryId) {
      errors.categoryId = "Category ID is required";
    } else if (!/^CAT-\d{3}$/i.test(modalForm.categoryId)) {
      errors.categoryId = "Category ID must be in format CAT-###";
    } else {
      // Check for duplicate category IDs (case-insensitive)
      const duplicate = items.find(cat => 
        cat.code && cat.code.toLowerCase() === modalForm.categoryId.toLowerCase()
      );
      if (duplicate) {
        errors.categoryId = "Category ID already exists";
      }
    }

    // Category name validation
    if (!modalForm.name.trim()) {
      errors.name = "Category name is required";
    } else if (modalForm.name.trim().length < 2) {
      errors.name = "Category name must be at least 2 characters";
    } else if (modalForm.name.trim().length > 120) {
      errors.name = "Category name must be less than 120 characters";
    } else {
      // Check for duplicate category names (case-insensitive)
      const duplicate = items.find(cat => 
        cat.name.toLowerCase() === modalForm.name.trim().toLowerCase()
      );
      if (duplicate) {
        errors.name = "Category name already exists";
      }
    }

    // Measurement type validation
    if (!modalForm.measurementType.trim()) {
      errors.measurementType = "Measurement type is required";
    } else if (modalForm.measurementType.trim().length > 50) {
      errors.measurementType = "Measurement type must be less than 50 characters";
    }

    // Description validation
    if (modalForm.description.trim().length > 300) {
      errors.description = "Description must be less than 300 characters";
    }

    setModalErrors(errors);
    return Object.keys(errors).length === 0;
  };


  // Save category (simple version without subcategories)
  const saveCategory = async () => {
    if (!validateCategoryForm()) {
      return;
    }

    try {
      setSaving(true);
      
      const payload = {
        name: modalForm.name.trim(),
        description: modalForm.description.trim(),
        measurementType: modalForm.measurementType.trim(),
        code: modalForm.categoryId
      };

      console.log("Sending payload:", payload); // Debug log

      const res = await http.post("/api/material-categories", payload);
      const { category, message } = res.data;
      
      // Add to items list
      setItems(prev => [category, ...prev]);
      
      // Show success toast
      toast(message || "Category created successfully");
      
      // Close modal
      closeModal();
      
    } catch (error) {
      console.error("Error saving category:", error);
      console.error("Error response:", error?.response?.data); // Debug log
      
      let errorMessage = "Failed to create category";
      
      if (error?.response?.status === 404) {
        errorMessage = "Category creation endpoint not found. Please check if you're logged in as an admin.";
      } else if (error?.response?.status === 401) {
        errorMessage = "Authentication required. Please log in as an admin.";
      } else if (error?.response?.status === 403) {
        errorMessage = "Access denied. Admin privileges required.";
      } else if (error?.response?.status === 400) {
        errorMessage = error?.response?.data?.message || "Invalid data provided. Please check your inputs.";
      } else if (error?.response?.data?.message) {
        errorMessage = error.response.data.message;
      } else if (error?.message) {
        errorMessage = error.message;
      }
      
      toast(errorMessage, "error");
    } finally {
      setSaving(false);
    }
  };

  const load = async () => {
    try {
      setLoading(true);
      const res = await http.get("/api/material-categories");
      
      const arr = Array.isArray(res?.data?.categories)
        ? res.data.categories
        : Array.isArray(res?.data)
          ? res.data
          : Array.isArray(res?.data?.data)
            ? res.data.data
            : [];
      
      console.log("Loaded categories:", arr); // Debug log
      setItems(arr);
    } catch (e) {
      console.error("Error loading categories:", e);
      if (e?.response?.status === 404) {
        setError("Material categories endpoint not found. Please check if you're logged in as an admin.");
      } else if (e?.response?.status === 401) {
        setError("Authentication required. Please log in as an admin to access this page.");
      } else {
        setError(e?.response?.data?.message || e?.message || "Failed to load categories");
      }
    } finally {
      setLoading(false);
    }
  };

  // Generate codes for existing categories
  const generateCodes = async () => {
    try {
      setSaving(true);
      const res = await http.post("/api/material-categories/generate-codes");
      const { updated, message } = res.data;
      
      toast(message || `Updated ${updated} categories with new CAT-### codes`);
      
      // Reload the categories to show the updated codes
      await load();
    } catch (error) {
      console.error("Error generating codes:", error);
      toast("Failed to generate category codes", "error");
    } finally {
      setSaving(false);
    }
  };

  const startEdit = (cat) => {
    setActionError("");
    setEditingId(cat._id);
    setEditName(cat.name || "");
    setEditDesc(cat.description || "");
  };

  const cancelEdit = () => {
    setEditingId("");
    setEditName("");
    setEditDesc("");
  };

  const saveEdit = async (id) => {
    try {
      setActionError("");
      const payload = { name: editName.trim(), description: (editDesc||"").trim() };
      if (!payload.name) { setActionError("Name is required"); return; }
      // optimistic
      setItems(prev => prev.map(x => x._id === id ? { ...x, name: payload.name, description: payload.description } : x));
      await http.put(`/api/material-categories/${id}`, payload);
      setSuccess("Category updated");
      cancelEdit();
    } catch (e) {
      setActionError(e?.response?.data?.message || e?.message || "Update failed");
      await load(); // revert
    }
  };

  const deleteCat = async (id) => {
    try {
      setActionError("");
      const ok = window.confirm("Delete this category?");
      if (!ok) return;
      // optimistic
      const prev = items;
      setItems(prev.filter(x => x._id !== id));
      await http.delete(`/api/material-categories/${id}`);
      setSuccess("Category deleted");
    } catch (e) {
      setActionError(e?.response?.data?.message || e?.message || "Delete failed");
      await load();
    }
  };

  useEffect(() => { load(); }, []);


  if (loading) return (
    <div style={{ display:'flex', minHeight:'100vh', background:'#f8fafb' }}>
      <SupplierSidebar />
      <div style={{ flex:1, padding:24 }}>Loading…</div>
    </div>
  );
  if (error) return (
    <div style={{ display:'flex', minHeight:'100vh', background:'#f8fafb' }}>
      <SupplierSidebar />
      <div style={{ flex:1, padding:24, color:'#b91c1c' }}>{error}</div>
    </div>
  );

  return (
    <div style={{ display:'flex', minHeight:'100vh', background:'#f8fafb' }}>
      <SupplierSidebar />
      <div style={{ flex:1, padding:24, maxWidth: 900, margin: '0 auto' }}>
      <h1 className="text-2xl font-bold" style={{ margin: 0 }}>Material Categories</h1>

      {success && (
        <div style={{ marginTop:12, background:'#ecfdf5', border:'1px solid #a7f3d0', color:'#065f46', borderRadius:12, padding:12 }}>
          {success}
        </div>
      )}
      {actionError && (
        <div style={{ marginTop:12, background:'#fef2f2', border:'1px solid #fecaca', color:'#991b1b', borderRadius:12, padding:12 }}>
          {actionError}
        </div>
      )}

      <div style={{ marginTop:12, display:'flex', justifyContent:'space-between', alignItems:'center' }}>
        <h2 style={{ margin:0, fontSize:18, fontWeight:600 }}>Categories</h2>
        <div style={{ display:'flex', gap:8 }}>
          <button 
            onClick={openModal}
            style={{ 
              background:'#1E7F3B', 
              color:'#fff', 
              border:'none', 
              padding:'10px 16px', 
              borderRadius:8, 
              cursor:'pointer',
              fontWeight:500
            }}
          >
            + Add Category
          </button>
          <button 
            onClick={generateCodes}
            style={{ 
              background:'#f59e0b', 
              color:'#fff', 
              border:'none', 
              padding:'10px 16px', 
              borderRadius:8, 
              cursor:'pointer',
              fontWeight:500
            }}
          >
            Fix Category IDs
          </button>
        </div>
      </div>

      {/* Search & Filters */}
      <div style={{ marginTop:12, background:'#fff', border:'1px solid #e5e7eb', borderRadius:12, padding:12, display:'flex', gap:12, alignItems:'center', flexWrap:'wrap' }}>
        <input
          value={q}
          onChange={(e)=>setQ(e.target.value)}
          placeholder="Search by category name..."
          style={{ padding:10, borderRadius:8, border:'1px solid #e5e7eb', flex:'1 1 280px' }}
        />
        <select value={sort} onChange={(e)=>setSort(e.target.value)} style={{ padding:10, borderRadius:8, border:'1px solid #e5e7eb' }}>
          <option value="name-asc">Name A → Z</option>
          <option value="name-desc">Name Z → A</option>
          <option value="recent">Recently Added</option>
        </select>
        <div style={{ color:'#6b7280', fontSize:12 }}>
          {items.length} total
        </div>
      </div>

      <div style={{ marginTop:12, background:'#fff', border:'1px solid #e5e7eb', borderRadius:12 }}>
        <table style={{ width:'100%', borderCollapse:'collapse' }}>
          <thead>
            <tr style={{ background:'#f9fafb', color:'#6b7280', textAlign:'left' }}>
              <th style={{ padding:12 }}>Category ID</th>
              <th style={{ padding:12 }}>Name</th>
              <th style={{ padding:12 }}>Measurement Type</th>
              <th style={{ padding:12 }}>Description</th>
              <th style={{ padding:12, width: 220 }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {(() => {
              const searchTerm = q.toLowerCase();
              let data = !searchTerm ? items : items.filter(c =>
                (c.name||"").toLowerCase().includes(searchTerm)
              );
              if (sort === 'name-asc') data = [...data].sort((a,b)=> (a.name||'').localeCompare(b.name||''));
              if (sort === 'name-desc') data = [...data].sort((a,b)=> (b.name||'').localeCompare(a.name||''));
              if (sort === 'recent') data = [...data].sort((a,b)=> new Date(b.createdAt||0) - new Date(a.createdAt||0));
              if (data.length === 0) return (
                <tr><td colSpan={5} style={{ padding:16 }}>No categories</td></tr>
              );
              return data.map(c => (
                <tr key={c._id} style={{ borderTop:'1px solid #f1f5f9' }}>
                  <td style={{ padding:12, fontFamily:'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace' }}>
                    {c.code || '-'}
                  </td>
                  <td style={{ padding:12 }}>
                    {editingId === c._id ? (
                      <input value={editName} onChange={(e)=>setEditName(e.target.value)} style={{ padding:8, border:'1px solid #e5e7eb', borderRadius:6, width:'100%' }} />
                    ) : (
                      c.name
                    )}
                  </td>
                  <td style={{ padding:12 }}>
                    <span style={{ 
                      background: '#f3f4f6', 
                      color: '#374151', 
                      padding: '4px 8px', 
                      borderRadius: 6, 
                      fontSize: 12, 
                      fontWeight: 500 
                    }}>
                      {c.measurementType || '-'}
                    </span>
                  </td>
                  <td style={{ padding:12 }}>
                    {editingId === c._id ? (
                      <input value={editDesc} onChange={(e)=>setEditDesc(e.target.value)} style={{ padding:8, border:'1px solid #e5e7eb', borderRadius:6, width:'100%' }} />
                    ) : (
                      c.description
                    )}
                  </td>
                  <td style={{ padding:12 }}>
                    {editingId === c._id ? (
                      <div style={{ display:'flex', gap:8, flexWrap:'wrap' }}>
                        <button type="button" onClick={()=>saveEdit(c._id)} style={{ background:'#1E7F3B', color:'#fff', border:'none', padding:'8px 12px', borderRadius:6, cursor:'pointer' }}>Save</button>
                        <button type="button" onClick={cancelEdit} style={{ background:'#fff', border:'1px solid #e5e7eb', padding:'8px 12px', borderRadius:6, cursor:'pointer' }}>Cancel</button>
                      </div>
                    ) : (
                      <div style={{ display:'flex', gap:8, flexWrap:'wrap' }}>
                        <button type="button" onClick={()=>startEdit(c)} style={{ background:'#fff', border:'1px solid #e5e7eb', padding:'8px 12px', borderRadius:6, cursor:'pointer' }}>Edit</button>
                        <button type="button" onClick={()=>deleteCat(c._id)} style={{ background:'#ef4444', color:'#fff', border:'none', padding:'8px 12px', borderRadius:6, cursor:'pointer' }}>Delete</button>
                      </div>
                    )}
                  </td>
                </tr>
              ));
            })()}
          </tbody>
        </table>
      </div>

      {/* Toast Notifications */}
      <div style={{ 
        position: 'fixed', 
        top: 20, 
        right: 20, 
        zIndex: 1000,
        display: 'flex',
        flexDirection: 'column',
        gap: 8
      }}>
        {toasts.map(toast => (
          <div
            key={toast.id}
            style={{
              background: toast.variant === 'error' ? '#fef2f2' : '#ecfdf5',
              border: `1px solid ${toast.variant === 'error' ? '#fecaca' : '#a7f3d0'}`,
              color: toast.variant === 'error' ? '#991b1b' : '#065f46',
              padding: '12px 16px',
              borderRadius: 8,
              minWidth: 300,
              boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
            }}
          >
            {toast.message}
          </div>
        ))}
      </div>

      {/* Add Category Modal */}
      {modalOpen && (
        <div style={{ 
          position: 'fixed', 
          inset: 0, 
          background: 'rgba(0,0,0,0.5)', 
          display: 'flex', 
          alignItems: 'center', 
          justifyContent: 'center', 
          zIndex: 50 
        }}>
          <div style={{ 
            background: '#fff', 
            borderRadius: 12, 
            border: '1px solid #e5e7eb', 
            padding: 24, 
            width: 'min(800px, 90vw)',
            maxHeight: '90vh',
            overflow: 'auto'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
              <h3 style={{ margin: 0, fontSize: 20, fontWeight: 600 }}>Add New Category</h3>
              <button 
                onClick={closeModal}
                style={{ 
                  border: 'none', 
                  background: 'transparent', 
                  fontSize: 24, 
                  cursor: 'pointer',
                  color: '#6b7280'
                }}
              >
                ×
              </button>
            </div>

            <div style={{ display: 'grid', gap: 16 }}>
              {/* Category ID (read-only) */}
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500, color: '#374151' }}>
                  Category ID
                </label>
                <input
                  value={modalForm.categoryId}
                  readOnly
                  style={{ 
                    padding: 10, 
                    borderRadius: 8, 
                    border: `1px solid ${modalErrors.categoryId ? '#ef4444' : '#e5e7eb'}`, 
                    background: '#f9fafb',
                    fontFamily: 'ui-monospace, monospace',
                    width: '100%'
                  }}
                />
                {modalErrors.categoryId && (
                  <div style={{ color: '#ef4444', fontSize: 12, marginTop: 4 }}>
                    {modalErrors.categoryId}
                  </div>
                )}
                <div style={{ fontSize: 11, color: '#6b7280', marginTop: 2 }}>
                  Next available ID for use in Inventory Management
                </div>
              </div>

              {/* Category Name */}
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500, color: '#374151' }}>
                  Category Name *
                </label>
                <input
                  value={modalForm.name}
                  onChange={(e) => setModalForm(prev => ({ ...prev, name: e.target.value }))}
                  placeholder="Enter category name"
                  style={{ 
                    padding: 10, 
                    borderRadius: 8, 
                    border: `1px solid ${modalErrors.name ? '#ef4444' : '#e5e7eb'}`, 
                    width: '100%'
                  }}
                />
                {modalErrors.name && (
                  <div style={{ color: '#ef4444', fontSize: 12, marginTop: 4 }}>
                    {modalErrors.name}
                  </div>
                )}
                <div style={{ fontSize: 11, color: '#6b7280', marginTop: 2 }}>
                  Must be unique, minimum 2 characters
                </div>
              </div>

              {/* Measurement Type */}
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500, color: '#374151' }}>
                  Measurement Type / Unit *
                </label>
                <input
                  value={modalForm.measurementType}
                  onChange={(e) => setModalForm(prev => ({ ...prev, measurementType: e.target.value }))}
                  placeholder="e.g., kg, units, size, bundles, ft, inches"
                  list="measurementTypes"
                  style={{ 
                    padding: 10, 
                    borderRadius: 8, 
                    border: `1px solid ${modalErrors.measurementType ? '#ef4444' : '#e5e7eb'}`, 
                    width: '100%'
                  }}
                />
                <datalist id="measurementTypes">
                  <option value="kg" />
                  <option value="units" />
                  <option value="size (ft)" />
                  <option value="size (inches)" />
                  <option value="bundles" />
                  <option value="pieces" />
                  <option value="liters" />
                  <option value="meters" />
                  <option value="boxes" />
                  <option value="bags" />
                </datalist>
                {modalErrors.measurementType && (
                  <div style={{ color: '#ef4444', fontSize: 12, marginTop: 4 }}>
                    {modalErrors.measurementType}
                  </div>
                )}
                <div style={{ fontSize: 11, color: '#6b7280', marginTop: 2 }}>
                  How this category is measured (e.g., Coconut Husk → kg, Timber → size)
                </div>
              </div>

              {/* Description */}
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500, color: '#374151' }}>
                  Description
                </label>
                <textarea
                  value={modalForm.description}
                  onChange={(e) => setModalForm(prev => ({ ...prev, description: e.target.value }))}
                  placeholder="Enter description (optional)"
                  rows={3}
                  style={{ 
                    padding: 10, 
                    borderRadius: 8, 
                    border: `1px solid ${modalErrors.description ? '#ef4444' : '#e5e7eb'}`, 
                    width: '100%',
                    resize: 'vertical'
                  }}
                />
                {modalErrors.description && (
                  <div style={{ color: '#ef4444', fontSize: 12, marginTop: 4 }}>
                    {modalErrors.description}
                  </div>
                )}
                <div style={{ fontSize: 11, color: '#6b7280', marginTop: 2 }}>
                  {modalForm.description.length}/300 characters
                </div>
              </div>
            </div>

            {/* Modal Actions */}
            <div style={{ display: 'flex', gap: 12, justifyContent: 'flex-end', marginTop: 24 }}>
              <button
                type="button"
                onClick={closeModal}
                style={{
                  background: '#fff',
                  border: '1px solid #d1d5db',
                  padding: '10px 16px',
                  borderRadius: 8,
                  cursor: 'pointer'
                }}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={saveCategory}
                disabled={saving}
                style={{
                  background: '#1E7F3B',
                  color: '#fff',
                  border: 'none',
                  padding: '10px 16px',
                  borderRadius: 8,
                  cursor: saving ? 'not-allowed' : 'pointer',
                  opacity: saving ? 0.7 : 1
                }}
              >
                {saving ? 'Saving...' : 'Save Category'}
              </button>
            </div>
          </div>
        </div>
      )}
      </div>
    </div>
  );
}
